version: '3.1'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
  mysql:
    network_mode: "host"
    environment:
        MYSQL_ROOT_PASSWORD: "root123456"
        MYSQL_USER: 'caper'
        MYSQL_PASS: 'caper123456'
    image: mysql
    restart: always
    volumes:
        - "./db:/var/lib/mysql"
        - "./conf/my.cnf:/etc/my.cnf"
        - "./init:/docker-entrypoint-initdb.d/"
    ports:
        - "3306:3306"